# Generated by Django 4.1 on 2022-09-04 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveBigIntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('security_code', models.PositiveBigIntegerField()),
                ('start_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('QRcode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction_date', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inSightapi.card')),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inSightapi.cardholder')),
                ('store', models.ManyToManyField(to='inSightapi.store')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inSightapi.transactiontype')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cardholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inSightapi.cardholder'),
        ),
    ]
