# Generated by Django 4.1 on 2022-09-02 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('expiration_date', models.PositiveSmallIntegerField()),
                ('security_code', models.PositiveSmallIntegerField()),
                ('start_balance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('QRcode', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Card_Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('transaction_date', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inSightapi.card')),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inSightapi.card_holder')),
                ('store', models.ManyToManyField(to='inSightapi.store')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inSightapi.transaction_type')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inSightapi.card_holder'),
        ),
    ]
