# Generated by Django 4.1 on 2022-09-01 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inSightapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='holder',
            new_name='card_holder',
        ),
        migrations.RemoveField(
            model_name='card_holder',
            name='card_info',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='security_code',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inSightapi.card'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='card_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inSightapi.card_holder'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inSightapi.transaction_type'),
        ),
    ]
